//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingDetailsIntegration
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:MemberBankDetailIntegration")]
    public partial class SysError
    {
        
        private string sysmsgField;
        
        private int retryinminutesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sysmsg
        {
            get
            {
                return this.sysmsgField;
            }
            set
            {
                this.sysmsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int retryinminutes
        {
            get
            {
                return this.retryinminutesField;
            }
            set
            {
                this.retryinminutesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:MemberBankDetailIntegration")]
    public partial class BankDetail
    {
        
        private string descriptionField;
        
        private string accDepWithdrawField;
        
        private string accountHolderField;
        
        private string bankNameField;
        
        private string branchCodeField;
        
        private string accountTypeField;
        
        private string accountNumberField;
        
        private string effDateField;
        
        private string endDateField;
        
        private string bankXferEffField;
        
        private string rateChargeIndField;
        
        private string emplGroupField;
        
        private string emplDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string AccDepWithdraw
        {
            get
            {
                return this.accDepWithdrawField;
            }
            set
            {
                this.accDepWithdrawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string AccountHolder
        {
            get
            {
                return this.accountHolderField;
            }
            set
            {
                this.accountHolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string BankName
        {
            get
            {
                return this.bankNameField;
            }
            set
            {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string BranchCode
        {
            get
            {
                return this.branchCodeField;
            }
            set
            {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string AccountType
        {
            get
            {
                return this.accountTypeField;
            }
            set
            {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string EffDate
        {
            get
            {
                return this.effDateField;
            }
            set
            {
                this.effDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string BankXferEff
        {
            get
            {
                return this.bankXferEffField;
            }
            set
            {
                this.bankXferEffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string RateChargeInd
        {
            get
            {
                return this.rateChargeIndField;
            }
            set
            {
                this.rateChargeIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string EmplGroup
        {
            get
            {
                return this.emplGroupField;
            }
            set
            {
                this.emplGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string EmplDescription
        {
            get
            {
                return this.emplDescriptionField;
            }
            set
            {
                this.emplDescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:MemberBankDetailIntegration", ConfigurationName="BankingDetailsIntegration.MemberBankDetailIntegrationPortType")]
    public interface MemberBankDetailIntegrationPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="MemberBankDetailDetailRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankingDetailsIntegration.SysError), Action="MemberBankDetailDetailRequest", Name="SysError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankingDetailsIntegration.MemberBankDetailRequestResponse> MemberBankDetailRequestAsync(BankingDetailsIntegration.MemberBankDetailRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:MemberBankDetailIntegration")]
    public partial class MemberBankDetailInput
    {
        
        private string schemeField;
        
        private int memberNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int MemberNumber
        {
            get
            {
                return this.memberNumberField;
            }
            set
            {
                this.memberNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:MemberBankDetailIntegration")]
    public partial class MemberBankDetailResponse
    {
        
        private string messageField;
        
        private bool successField;
        
        private string schemeField;
        
        private System.Nullable<int> memberNumberField;
        
        private BankDetail[] bankDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> MemberNumber
        {
            get
            {
                return this.memberNumberField;
            }
            set
            {
                this.memberNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BankDetail[] BankDetails
        {
            get
            {
                return this.bankDetailsField;
            }
            set
            {
                this.bankDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MemberBankDetailRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MemberBankDetailIntegration", Order=0)]
        public BankingDetailsIntegration.MemberBankDetailInput MemberBankDetailInput;
        
        public MemberBankDetailRequestRequest()
        {
        }
        
        public MemberBankDetailRequestRequest(BankingDetailsIntegration.MemberBankDetailInput MemberBankDetailInput)
        {
            this.MemberBankDetailInput = MemberBankDetailInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MemberBankDetailRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MemberBankDetailIntegration", Order=0)]
        public BankingDetailsIntegration.MemberBankDetailResponse MemberBankDetailResponse;
        
        public MemberBankDetailRequestResponse()
        {
        }
        
        public MemberBankDetailRequestResponse(BankingDetailsIntegration.MemberBankDetailResponse MemberBankDetailResponse)
        {
            this.MemberBankDetailResponse = MemberBankDetailResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface MemberBankDetailIntegrationPortTypeChannel : BankingDetailsIntegration.MemberBankDetailIntegrationPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class MemberBankDetailIntegrationPortTypeClient : System.ServiceModel.ClientBase<BankingDetailsIntegration.MemberBankDetailIntegrationPortType>, BankingDetailsIntegration.MemberBankDetailIntegrationPortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MemberBankDetailIntegrationPortTypeClient() : 
                base(MemberBankDetailIntegrationPortTypeClient.GetDefaultBinding(), MemberBankDetailIntegrationPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MemberBankDetailIntegrationPort12.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MemberBankDetailIntegrationPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(MemberBankDetailIntegrationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), MemberBankDetailIntegrationPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MemberBankDetailIntegrationPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MemberBankDetailIntegrationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MemberBankDetailIntegrationPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MemberBankDetailIntegrationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MemberBankDetailIntegrationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankingDetailsIntegration.MemberBankDetailRequestResponse> BankingDetailsIntegration.MemberBankDetailIntegrationPortType.MemberBankDetailRequestAsync(BankingDetailsIntegration.MemberBankDetailRequestRequest request)
        {
            return base.Channel.MemberBankDetailRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankingDetailsIntegration.MemberBankDetailRequestResponse> MemberBankDetailRequestAsync(BankingDetailsIntegration.MemberBankDetailInput MemberBankDetailInput)
        {
            BankingDetailsIntegration.MemberBankDetailRequestRequest inValue = new BankingDetailsIntegration.MemberBankDetailRequestRequest();
            inValue.MemberBankDetailInput = MemberBankDetailInput;
            return ((BankingDetailsIntegration.MemberBankDetailIntegrationPortType)(this)).MemberBankDetailRequestAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MemberBankDetailIntegrationPort12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MemberBankDetailIntegrationPort12))
            {
                return new System.ServiceModel.EndpointAddress("https://webservicestest.medihelp.co.za/SoapErpQA/MemberBankDetailIntegration.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MemberBankDetailIntegrationPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.MemberBankDetailIntegrationPort12);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MemberBankDetailIntegrationPortTypeClient.GetEndpointAddress(EndpointConfiguration.MemberBankDetailIntegrationPort12);
        }
        
        public enum EndpointConfiguration
        {
            
            MemberBankDetailIntegrationPort12,
        }
    }
}
