//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerIntegrationService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class SysError
    {
        
        private string sysmsgField;
        
        private int retryinminutesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sysmsg
        {
            get
            {
                return this.sysmsgField;
            }
            set
            {
                this.sysmsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int retryinminutes
        {
            get
            {
                return this.retryinminutesField;
            }
            set
            {
                this.retryinminutesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:EmployerWebsiteIntegration", ConfigurationName="EmployerIntegrationService.EmployerWebsiteIntegrationPortType")]
    public interface EmployerWebsiteIntegrationPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="UpdatePostalAddress", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployerIntegrationService.SysError), Action="UpdatePostalAddress", Name="SysError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployerIntegrationService.UpdatePostalAddressResponse> UpdatePostalAddressAsync(EmployerIntegrationService.UpdatePostalAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UpdateStreetAddress", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployerIntegrationService.SysError), Action="UpdateStreetAddress", Name="SysError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployerIntegrationService.UpdateStreetAddressResponse> UpdateStreetAddressAsync(EmployerIntegrationService.UpdateStreetAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="EmployerMbrCertificate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployerIntegrationService.SysError), Action="EmployerMbrCertificate", Name="SysError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployerIntegrationService.EmployerMbrCertificateResponse1> EmployerMbrCertificateAsync(EmployerIntegrationService.EmployerMbrCertificateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SubscriptionBreakdownRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployerIntegrationService.SysError), Action="SubscriptionBreakdownRequest", Name="SysError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployerIntegrationService.SubscriptionBreakdownRequestResponse> SubscriptionBreakdownRequestAsync(EmployerIntegrationService.SubscriptionBreakdownRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="EmployerDetailRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployerIntegrationService.SysError), Action="EmployerDetailRequest", Name="SysError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployerIntegrationService.EmployerDetailRequestResponse> EmployerDetailRequestAsync(EmployerIntegrationService.EmployerDetailRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="EmployerContact", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployerIntegrationService.SysError), Action="EmployerContact", Name="SysError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployerIntegrationService.EmployerContactResponse1> EmployerContactAsync(EmployerIntegrationService.EmployerContactRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class PostalAddressInput
    {
        
        private string schemeField;
        
        private string employerNumberField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string addressLine4Field;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EmployerNumber
        {
            get
            {
                return this.employerNumberField;
            }
            set
            {
                this.employerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string AddressLine3
        {
            get
            {
                return this.addressLine3Field;
            }
            set
            {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string AddressLine4
        {
            get
            {
                return this.addressLine4Field;
            }
            set
            {
                this.addressLine4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class PostalAddressResponse
    {
        
        private string messageField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePostalAddressRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.PostalAddressInput PostalAddressInput;
        
        public UpdatePostalAddressRequest()
        {
        }
        
        public UpdatePostalAddressRequest(EmployerIntegrationService.PostalAddressInput PostalAddressInput)
        {
            this.PostalAddressInput = PostalAddressInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePostalAddressResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.PostalAddressResponse PostalAddressResponse;
        
        public UpdatePostalAddressResponse()
        {
        }
        
        public UpdatePostalAddressResponse(EmployerIntegrationService.PostalAddressResponse PostalAddressResponse)
        {
            this.PostalAddressResponse = PostalAddressResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class StreetAddressInput
    {
        
        private string schemeField;
        
        private string employerNumberField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string addressLine4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EmployerNumber
        {
            get
            {
                return this.employerNumberField;
            }
            set
            {
                this.employerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string AddressLine3
        {
            get
            {
                return this.addressLine3Field;
            }
            set
            {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string AddressLine4
        {
            get
            {
                return this.addressLine4Field;
            }
            set
            {
                this.addressLine4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class StreetAddressResponse
    {
        
        private string messageField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStreetAddressRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.StreetAddressInput StreetAddressInput;
        
        public UpdateStreetAddressRequest()
        {
        }
        
        public UpdateStreetAddressRequest(EmployerIntegrationService.StreetAddressInput StreetAddressInput)
        {
            this.StreetAddressInput = StreetAddressInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStreetAddressResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.StreetAddressResponse StreetAddressResponse;
        
        public UpdateStreetAddressResponse()
        {
        }
        
        public UpdateStreetAddressResponse(EmployerIntegrationService.StreetAddressResponse StreetAddressResponse)
        {
            this.StreetAddressResponse = StreetAddressResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class EmployerMbrCertificateInput
    {
        
        private string schemeField;
        
        private string memberNumberField;
        
        private string dependantField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MemberNumber
        {
            get
            {
                return this.memberNumberField;
            }
            set
            {
                this.memberNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Dependant
        {
            get
            {
                return this.dependantField;
            }
            set
            {
                this.dependantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class EmployerMbrCertificateResponse
    {
        
        private string messageField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployerMbrCertificateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.EmployerMbrCertificateInput EmployerMbrCertificateInput;
        
        public EmployerMbrCertificateRequest()
        {
        }
        
        public EmployerMbrCertificateRequest(EmployerIntegrationService.EmployerMbrCertificateInput EmployerMbrCertificateInput)
        {
            this.EmployerMbrCertificateInput = EmployerMbrCertificateInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployerMbrCertificateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.EmployerMbrCertificateResponse EmployerMbrCertificateResponse;
        
        public EmployerMbrCertificateResponse1()
        {
        }
        
        public EmployerMbrCertificateResponse1(EmployerIntegrationService.EmployerMbrCertificateResponse EmployerMbrCertificateResponse)
        {
            this.EmployerMbrCertificateResponse = EmployerMbrCertificateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class SubscriptionBreakdownInput
    {
        
        private string schemeField;
        
        private int memberNumberField;
        
        private System.Nullable<System.DateTime> dateEffectiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int MemberNumber
        {
            get
            {
                return this.memberNumberField;
            }
            set
            {
                this.memberNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> DateEffective
        {
            get
            {
                return this.dateEffectiveField;
            }
            set
            {
                this.dateEffectiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class SubscriptionBreakdownResponse
    {
        
        private string messageField;
        
        private bool successField;
        
        private string schemeField;
        
        private int memberNumberField;
        
        private System.Nullable<System.DateTime> dateEffectiveField;
        
        private decimal totalSubscriptionField;
        
        private System.Nullable<decimal> subsidyField;
        
        private decimal memberPortionField;
        
        private string subsidyFactorField;
        
        private System.Nullable<decimal> maxSubsCalculateField;
        
        private System.Nullable<decimal> maxSubsidyField;
        
        private Dependant[] dependantsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int MemberNumber
        {
            get
            {
                return this.memberNumberField;
            }
            set
            {
                this.memberNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> DateEffective
        {
            get
            {
                return this.dateEffectiveField;
            }
            set
            {
                this.dateEffectiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal TotalSubscription
        {
            get
            {
                return this.totalSubscriptionField;
            }
            set
            {
                this.totalSubscriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<decimal> Subsidy
        {
            get
            {
                return this.subsidyField;
            }
            set
            {
                this.subsidyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal MemberPortion
        {
            get
            {
                return this.memberPortionField;
            }
            set
            {
                this.memberPortionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SubsidyFactor
        {
            get
            {
                return this.subsidyFactorField;
            }
            set
            {
                this.subsidyFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<decimal> MaxSubsCalculate
        {
            get
            {
                return this.maxSubsCalculateField;
            }
            set
            {
                this.maxSubsCalculateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public System.Nullable<decimal> MaxSubsidy
        {
            get
            {
                return this.maxSubsidyField;
            }
            set
            {
                this.maxSubsidyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Dependant[] Dependants
        {
            get
            {
                return this.dependantsField;
            }
            set
            {
                this.dependantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:EmployerWebsiteIntegration")]
    public partial class Dependant
    {
        
        private string dependantNameField;
        
        private System.Nullable<int> dependantNumberField;
        
        private string dependantTypeField;
        
        private decimal coreSubscriptionField;
        
        private System.Nullable<decimal> savingsAmountField;
        
        private System.Nullable<decimal> lateJoinerPenaltyField;
        
        private decimal totMonthlySubscriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DependantName
        {
            get
            {
                return this.dependantNameField;
            }
            set
            {
                this.dependantNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> DependantNumber
        {
            get
            {
                return this.dependantNumberField;
            }
            set
            {
                this.dependantNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DependantType
        {
            get
            {
                return this.dependantTypeField;
            }
            set
            {
                this.dependantTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CoreSubscription
        {
            get
            {
                return this.coreSubscriptionField;
            }
            set
            {
                this.coreSubscriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> SavingsAmount
        {
            get
            {
                return this.savingsAmountField;
            }
            set
            {
                this.savingsAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> LateJoinerPenalty
        {
            get
            {
                return this.lateJoinerPenaltyField;
            }
            set
            {
                this.lateJoinerPenaltyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TotMonthlySubscription
        {
            get
            {
                return this.totMonthlySubscriptionField;
            }
            set
            {
                this.totMonthlySubscriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscriptionBreakdownRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.SubscriptionBreakdownInput SubscriptionBreakdownInput;
        
        public SubscriptionBreakdownRequestRequest()
        {
        }
        
        public SubscriptionBreakdownRequestRequest(EmployerIntegrationService.SubscriptionBreakdownInput SubscriptionBreakdownInput)
        {
            this.SubscriptionBreakdownInput = SubscriptionBreakdownInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscriptionBreakdownRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.SubscriptionBreakdownResponse SubscriptionBreakdownResponse;
        
        public SubscriptionBreakdownRequestResponse()
        {
        }
        
        public SubscriptionBreakdownRequestResponse(EmployerIntegrationService.SubscriptionBreakdownResponse SubscriptionBreakdownResponse)
        {
            this.SubscriptionBreakdownResponse = SubscriptionBreakdownResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class EmployerDetailInput
    {
        
        private string schemeField;
        
        private string employerNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EmployerNumber
        {
            get
            {
                return this.employerNumberField;
            }
            set
            {
                this.employerNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class EmployerDetailResponse
    {
        
        private string messageField;
        
        private bool successField;
        
        private string schemeField;
        
        private string employerNumberField;
        
        private string employerNameField;
        
        private string employerGroupTypeField;
        
        private string persalCodeField;
        
        private string classCodeField;
        
        private string postalAddressLine1Field;
        
        private string postalAddressLine2Field;
        
        private string postalAddressLine3Field;
        
        private string postalAddressLine4Field;
        
        private string postalCodeField;
        
        private string streetAddressLine1Field;
        
        private string streetAddressLine2Field;
        
        private string streetAddressLine3Field;
        
        private string streetAddressLine4Field;
        
        private string payRefNumberField;
        
        private string payAreaField;
        
        private string payAreaDescriptionField;
        
        private string payAreaConsultantField;
        
        private string contactUserField;
        
        private string contactUserNameField;
        
        private string contactUserEmailField;
        
        private string contactUserTelWorkField;
        
        private string contactFaxDialcodeField;
        
        private string contactFaxPhoneNrField;
        
        private string clientRelationUserField;
        
        private string clientRelationUserNameField;
        
        private string clientRelationUserEmailField;
        
        private string clientRelationUserTelWorkField;
        
        private string clientFaxDialcodeField;
        
        private string clientFaxPhoneNrField;
        
        private string bankAccountTypeField;
        
        private string bankBranchNumberField;
        
        private string bankAccountNumberField;
        
        private string dateAccountEffField;
        
        private string dateAccountEndField;
        
        private string bankXferEffField;
        
        private string brokerHouseNumberField;
        
        private string brokerHouseNameField;
        
        private string brokerNumberField;
        
        private string brokerNameField;
        
        private string brokerEmailField;
        
        private string brokerLinkEffField;
        
        private string brokerLinkEndField;
        
        private BrokerPhoneNumber[] brokerPhoneNumbersField;
        
        private EmployerContact[] employerContactsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EmployerNumber
        {
            get
            {
                return this.employerNumberField;
            }
            set
            {
                this.employerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EmployerName
        {
            get
            {
                return this.employerNameField;
            }
            set
            {
                this.employerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string EmployerGroupType
        {
            get
            {
                return this.employerGroupTypeField;
            }
            set
            {
                this.employerGroupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PersalCode
        {
            get
            {
                return this.persalCodeField;
            }
            set
            {
                this.persalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ClassCode
        {
            get
            {
                return this.classCodeField;
            }
            set
            {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PostalAddressLine1
        {
            get
            {
                return this.postalAddressLine1Field;
            }
            set
            {
                this.postalAddressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string PostalAddressLine2
        {
            get
            {
                return this.postalAddressLine2Field;
            }
            set
            {
                this.postalAddressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PostalAddressLine3
        {
            get
            {
                return this.postalAddressLine3Field;
            }
            set
            {
                this.postalAddressLine3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PostalAddressLine4
        {
            get
            {
                return this.postalAddressLine4Field;
            }
            set
            {
                this.postalAddressLine4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string StreetAddressLine1
        {
            get
            {
                return this.streetAddressLine1Field;
            }
            set
            {
                this.streetAddressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string StreetAddressLine2
        {
            get
            {
                return this.streetAddressLine2Field;
            }
            set
            {
                this.streetAddressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string StreetAddressLine3
        {
            get
            {
                return this.streetAddressLine3Field;
            }
            set
            {
                this.streetAddressLine3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string StreetAddressLine4
        {
            get
            {
                return this.streetAddressLine4Field;
            }
            set
            {
                this.streetAddressLine4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string PayRefNumber
        {
            get
            {
                return this.payRefNumberField;
            }
            set
            {
                this.payRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string PayArea
        {
            get
            {
                return this.payAreaField;
            }
            set
            {
                this.payAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string PayAreaDescription
        {
            get
            {
                return this.payAreaDescriptionField;
            }
            set
            {
                this.payAreaDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string PayAreaConsultant
        {
            get
            {
                return this.payAreaConsultantField;
            }
            set
            {
                this.payAreaConsultantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ContactUser
        {
            get
            {
                return this.contactUserField;
            }
            set
            {
                this.contactUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string ContactUserName
        {
            get
            {
                return this.contactUserNameField;
            }
            set
            {
                this.contactUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public string ContactUserEmail
        {
            get
            {
                return this.contactUserEmailField;
            }
            set
            {
                this.contactUserEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string ContactUserTelWork
        {
            get
            {
                return this.contactUserTelWorkField;
            }
            set
            {
                this.contactUserTelWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string ContactFaxDialcode
        {
            get
            {
                return this.contactFaxDialcodeField;
            }
            set
            {
                this.contactFaxDialcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string ContactFaxPhoneNr
        {
            get
            {
                return this.contactFaxPhoneNrField;
            }
            set
            {
                this.contactFaxPhoneNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ClientRelationUser
        {
            get
            {
                return this.clientRelationUserField;
            }
            set
            {
                this.clientRelationUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string ClientRelationUserName
        {
            get
            {
                return this.clientRelationUserNameField;
            }
            set
            {
                this.clientRelationUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=29)]
        public string ClientRelationUserEmail
        {
            get
            {
                return this.clientRelationUserEmailField;
            }
            set
            {
                this.clientRelationUserEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string ClientRelationUserTelWork
        {
            get
            {
                return this.clientRelationUserTelWorkField;
            }
            set
            {
                this.clientRelationUserTelWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string ClientFaxDialcode
        {
            get
            {
                return this.clientFaxDialcodeField;
            }
            set
            {
                this.clientFaxDialcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string ClientFaxPhoneNr
        {
            get
            {
                return this.clientFaxPhoneNrField;
            }
            set
            {
                this.clientFaxPhoneNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string BankAccountType
        {
            get
            {
                return this.bankAccountTypeField;
            }
            set
            {
                this.bankAccountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string BankBranchNumber
        {
            get
            {
                return this.bankBranchNumberField;
            }
            set
            {
                this.bankBranchNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string BankAccountNumber
        {
            get
            {
                return this.bankAccountNumberField;
            }
            set
            {
                this.bankAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string DateAccountEff
        {
            get
            {
                return this.dateAccountEffField;
            }
            set
            {
                this.dateAccountEffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string DateAccountEnd
        {
            get
            {
                return this.dateAccountEndField;
            }
            set
            {
                this.dateAccountEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string BankXferEff
        {
            get
            {
                return this.bankXferEffField;
            }
            set
            {
                this.bankXferEffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string BrokerHouseNumber
        {
            get
            {
                return this.brokerHouseNumberField;
            }
            set
            {
                this.brokerHouseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string BrokerHouseName
        {
            get
            {
                return this.brokerHouseNameField;
            }
            set
            {
                this.brokerHouseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string BrokerNumber
        {
            get
            {
                return this.brokerNumberField;
            }
            set
            {
                this.brokerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string BrokerName
        {
            get
            {
                return this.brokerNameField;
            }
            set
            {
                this.brokerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string BrokerEmail
        {
            get
            {
                return this.brokerEmailField;
            }
            set
            {
                this.brokerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string BrokerLinkEff
        {
            get
            {
                return this.brokerLinkEffField;
            }
            set
            {
                this.brokerLinkEffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string BrokerLinkEnd
        {
            get
            {
                return this.brokerLinkEndField;
            }
            set
            {
                this.brokerLinkEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BrokerPhoneNumber[] BrokerPhoneNumbers
        {
            get
            {
                return this.brokerPhoneNumbersField;
            }
            set
            {
                this.brokerPhoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EmployerContact[] EmployerContacts
        {
            get
            {
                return this.employerContactsField;
            }
            set
            {
                this.employerContactsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:EmployerWebsiteIntegration")]
    public partial class BrokerPhoneNumber
    {
        
        private string typeField;
        
        private string dialCodeField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string DialCode
        {
            get
            {
                return this.dialCodeField;
            }
            set
            {
                this.dialCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:EmployerWebsiteIntegration")]
    public partial class EmployerContact
    {
        
        private string contTitleField;
        
        private string contInitField;
        
        private string contAliasField;
        
        private string contSurnameField;
        
        private string desigCodeField;
        
        private string desigGroupField;
        
        private string contEmailField;
        
        private string contDialCodeField;
        
        private string contPhoneNrField;
        
        private string contCellNrField;
        
        private string contFaxDialCodeField;
        
        private string contFaxPhoneNrField;
        
        private string contBirthdayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContTitle
        {
            get
            {
                return this.contTitleField;
            }
            set
            {
                this.contTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContInit
        {
            get
            {
                return this.contInitField;
            }
            set
            {
                this.contInitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContAlias
        {
            get
            {
                return this.contAliasField;
            }
            set
            {
                this.contAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContSurname
        {
            get
            {
                return this.contSurnameField;
            }
            set
            {
                this.contSurnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DesigCode
        {
            get
            {
                return this.desigCodeField;
            }
            set
            {
                this.desigCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DesigGroup
        {
            get
            {
                return this.desigGroupField;
            }
            set
            {
                this.desigGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContEmail
        {
            get
            {
                return this.contEmailField;
            }
            set
            {
                this.contEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContDialCode
        {
            get
            {
                return this.contDialCodeField;
            }
            set
            {
                this.contDialCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContPhoneNr
        {
            get
            {
                return this.contPhoneNrField;
            }
            set
            {
                this.contPhoneNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContCellNr
        {
            get
            {
                return this.contCellNrField;
            }
            set
            {
                this.contCellNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContFaxDialCode
        {
            get
            {
                return this.contFaxDialCodeField;
            }
            set
            {
                this.contFaxDialCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContFaxPhoneNr
        {
            get
            {
                return this.contFaxPhoneNrField;
            }
            set
            {
                this.contFaxPhoneNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContBirthday
        {
            get
            {
                return this.contBirthdayField;
            }
            set
            {
                this.contBirthdayField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployerDetailRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.EmployerDetailInput EmployerDetailInput;
        
        public EmployerDetailRequestRequest()
        {
        }
        
        public EmployerDetailRequestRequest(EmployerIntegrationService.EmployerDetailInput EmployerDetailInput)
        {
            this.EmployerDetailInput = EmployerDetailInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployerDetailRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.EmployerDetailResponse EmployerDetailResponse;
        
        public EmployerDetailRequestResponse()
        {
        }
        
        public EmployerDetailRequestResponse(EmployerIntegrationService.EmployerDetailResponse EmployerDetailResponse)
        {
            this.EmployerDetailResponse = EmployerDetailResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class EmployerContactInput
    {
        
        private string schemeField;
        
        private string employerNumberField;
        
        private string payAreaField;
        
        private EmployerContact[] employerContactsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EmployerNumber
        {
            get
            {
                return this.employerNumberField;
            }
            set
            {
                this.employerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PayArea
        {
            get
            {
                return this.payAreaField;
            }
            set
            {
                this.payAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EmployerContact[] EmployerContacts
        {
            get
            {
                return this.employerContactsField;
            }
            set
            {
                this.employerContactsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:EmployerWebsiteIntegration")]
    public partial class EmployerContactResponse
    {
        
        private string messageField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployerContactRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.EmployerContactInput EmployerContactInput;
        
        public EmployerContactRequest()
        {
        }
        
        public EmployerContactRequest(EmployerIntegrationService.EmployerContactInput EmployerContactInput)
        {
            this.EmployerContactInput = EmployerContactInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployerContactResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:EmployerWebsiteIntegration", Order=0)]
        public EmployerIntegrationService.EmployerContactResponse EmployerContactResponse;
        
        public EmployerContactResponse1()
        {
        }
        
        public EmployerContactResponse1(EmployerIntegrationService.EmployerContactResponse EmployerContactResponse)
        {
            this.EmployerContactResponse = EmployerContactResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface EmployerWebsiteIntegrationPortTypeChannel : EmployerIntegrationService.EmployerWebsiteIntegrationPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class EmployerWebsiteIntegrationPortTypeClient : System.ServiceModel.ClientBase<EmployerIntegrationService.EmployerWebsiteIntegrationPortType>, EmployerIntegrationService.EmployerWebsiteIntegrationPortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmployerWebsiteIntegrationPortTypeClient() : 
                base(EmployerWebsiteIntegrationPortTypeClient.GetDefaultBinding(), EmployerWebsiteIntegrationPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EmployerWebsiteIntegrationPort12.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployerWebsiteIntegrationPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(EmployerWebsiteIntegrationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), EmployerWebsiteIntegrationPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployerWebsiteIntegrationPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmployerWebsiteIntegrationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployerWebsiteIntegrationPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmployerWebsiteIntegrationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployerWebsiteIntegrationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployerIntegrationService.UpdatePostalAddressResponse> EmployerIntegrationService.EmployerWebsiteIntegrationPortType.UpdatePostalAddressAsync(EmployerIntegrationService.UpdatePostalAddressRequest request)
        {
            return base.Channel.UpdatePostalAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployerIntegrationService.UpdatePostalAddressResponse> UpdatePostalAddressAsync(EmployerIntegrationService.PostalAddressInput PostalAddressInput)
        {
            EmployerIntegrationService.UpdatePostalAddressRequest inValue = new EmployerIntegrationService.UpdatePostalAddressRequest();
            inValue.PostalAddressInput = PostalAddressInput;
            return ((EmployerIntegrationService.EmployerWebsiteIntegrationPortType)(this)).UpdatePostalAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployerIntegrationService.UpdateStreetAddressResponse> EmployerIntegrationService.EmployerWebsiteIntegrationPortType.UpdateStreetAddressAsync(EmployerIntegrationService.UpdateStreetAddressRequest request)
        {
            return base.Channel.UpdateStreetAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployerIntegrationService.UpdateStreetAddressResponse> UpdateStreetAddressAsync(EmployerIntegrationService.StreetAddressInput StreetAddressInput)
        {
            EmployerIntegrationService.UpdateStreetAddressRequest inValue = new EmployerIntegrationService.UpdateStreetAddressRequest();
            inValue.StreetAddressInput = StreetAddressInput;
            return ((EmployerIntegrationService.EmployerWebsiteIntegrationPortType)(this)).UpdateStreetAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployerIntegrationService.EmployerMbrCertificateResponse1> EmployerIntegrationService.EmployerWebsiteIntegrationPortType.EmployerMbrCertificateAsync(EmployerIntegrationService.EmployerMbrCertificateRequest request)
        {
            return base.Channel.EmployerMbrCertificateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployerIntegrationService.EmployerMbrCertificateResponse1> EmployerMbrCertificateAsync(EmployerIntegrationService.EmployerMbrCertificateInput EmployerMbrCertificateInput)
        {
            EmployerIntegrationService.EmployerMbrCertificateRequest inValue = new EmployerIntegrationService.EmployerMbrCertificateRequest();
            inValue.EmployerMbrCertificateInput = EmployerMbrCertificateInput;
            return ((EmployerIntegrationService.EmployerWebsiteIntegrationPortType)(this)).EmployerMbrCertificateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployerIntegrationService.SubscriptionBreakdownRequestResponse> EmployerIntegrationService.EmployerWebsiteIntegrationPortType.SubscriptionBreakdownRequestAsync(EmployerIntegrationService.SubscriptionBreakdownRequestRequest request)
        {
            return base.Channel.SubscriptionBreakdownRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployerIntegrationService.SubscriptionBreakdownRequestResponse> SubscriptionBreakdownRequestAsync(EmployerIntegrationService.SubscriptionBreakdownInput SubscriptionBreakdownInput)
        {
            EmployerIntegrationService.SubscriptionBreakdownRequestRequest inValue = new EmployerIntegrationService.SubscriptionBreakdownRequestRequest();
            inValue.SubscriptionBreakdownInput = SubscriptionBreakdownInput;
            return ((EmployerIntegrationService.EmployerWebsiteIntegrationPortType)(this)).SubscriptionBreakdownRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployerIntegrationService.EmployerDetailRequestResponse> EmployerIntegrationService.EmployerWebsiteIntegrationPortType.EmployerDetailRequestAsync(EmployerIntegrationService.EmployerDetailRequestRequest request)
        {
            return base.Channel.EmployerDetailRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployerIntegrationService.EmployerDetailRequestResponse> EmployerDetailRequestAsync(EmployerIntegrationService.EmployerDetailInput EmployerDetailInput)
        {
            EmployerIntegrationService.EmployerDetailRequestRequest inValue = new EmployerIntegrationService.EmployerDetailRequestRequest();
            inValue.EmployerDetailInput = EmployerDetailInput;
            return ((EmployerIntegrationService.EmployerWebsiteIntegrationPortType)(this)).EmployerDetailRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployerIntegrationService.EmployerContactResponse1> EmployerIntegrationService.EmployerWebsiteIntegrationPortType.EmployerContactAsync(EmployerIntegrationService.EmployerContactRequest request)
        {
            return base.Channel.EmployerContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployerIntegrationService.EmployerContactResponse1> EmployerContactAsync(EmployerIntegrationService.EmployerContactInput EmployerContactInput)
        {
            EmployerIntegrationService.EmployerContactRequest inValue = new EmployerIntegrationService.EmployerContactRequest();
            inValue.EmployerContactInput = EmployerContactInput;
            return ((EmployerIntegrationService.EmployerWebsiteIntegrationPortType)(this)).EmployerContactAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmployerWebsiteIntegrationPort12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmployerWebsiteIntegrationPort12))
            {
                return new System.ServiceModel.EndpointAddress("https://webservicestest.medihelp.co.za/SoapErpQA/EmployerWebsiteIntegration.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EmployerWebsiteIntegrationPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.EmployerWebsiteIntegrationPort12);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EmployerWebsiteIntegrationPortTypeClient.GetEndpointAddress(EndpointConfiguration.EmployerWebsiteIntegrationPort12);
        }
        
        public enum EndpointConfiguration
        {
            
            EmployerWebsiteIntegrationPort12,
        }
    }
}
